// CLI coding tools and their configuration metadata
export const CLI_TOOLS = {
  claude: {
    id: 'claude',
    name: 'Claude Code',
    icon: 'CC',
    color: '#D97757',
    description: 'Anthropic Claude Code CLI',
    configType: 'env',
    envVars: {
      baseUrl: 'ANTHROPIC_BASE_URL',
      model: 'ANTHROPIC_MODEL',
      opusModel: 'ANTHROPIC_DEFAULT_OPUS_MODEL',
      sonnetModel: 'ANTHROPIC_DEFAULT_SONNET_MODEL',
      haikuModel: 'ANTHROPIC_DEFAULT_HAIKU_MODEL',
    },
    defaultModels: [
      { id: 'opus', name: 'Claude Opus' },
      { id: 'sonnet', name: 'Claude Sonnet' },
      { id: 'haiku', name: 'Claude Haiku' },
    ],
  },
  codex: {
    id: 'codex',
    name: 'OpenAI Codex',
    icon: 'OC',
    color: '#10A37F',
    description: 'OpenAI Codex CLI',
    configType: 'custom',
  },
  opencode: {
    id: 'opencode',
    name: 'OpenCode',
    icon: 'OE',
    color: '#E87040',
    description: 'OpenCode AI Terminal Assistant',
    configType: 'custom',
  },
  copilot: {
    id: 'copilot',
    name: 'GitHub Copilot',
    icon: 'GH',
    color: '#1F6FEB',
    description: 'GitHub Copilot IDE with MITM',
    configType: 'mitm',
  },
  cursor: {
    id: 'cursor',
    name: 'Cursor',
    icon: 'CU',
    color: '#000000',
    description: 'Cursor AI Code Editor',
    configType: 'guide',
    guideSteps: [
      { step: 1, title: 'Open Settings', desc: 'Go to Settings → Models' },
      { step: 2, title: 'Enable OpenAI API', desc: 'Enable OpenAI API key option' },
      { step: 3, title: 'Base URL', value: '{{baseUrl}}', copyable: true },
      { step: 4, title: 'API Key', type: 'apiKeySelector' },
      { step: 5, title: 'Add Custom Model', desc: 'Click View All Model → Add Custom Model' },
      { step: 6, title: 'Select Model', type: 'modelSelector' },
    ],
  },
  cline: {
    id: 'cline',
    name: 'Cline',
    icon: 'CL',
    color: '#00D1B2',
    description: 'Cline AI Coding Assistant',
    configType: 'custom',
  },
  hermes: {
    id: 'hermes',
    name: 'Hermes Agent',
    icon: 'HA',
    color: '#8B5CF6',
    description: 'Nous Research self-improving AI agent',
    configType: 'custom',
  },
  continue: {
    id: 'continue',
    name: 'Continue',
    icon: 'CO',
    color: '#7C3AED',
    description: 'Continue AI Assistant',
    configType: 'guide',
    guideSteps: [
      { step: 1, title: 'Open Config', desc: 'Open Continue configuration file' },
      { step: 2, title: 'API Key', type: 'apiKeySelector' },
      { step: 3, title: 'Select Model', type: 'modelSelector' },
      { step: 4, title: 'Add Model Config', desc: 'Add the following configuration to your models array:' },
    ],
  },
  qwen: {
    id: 'qwen',
    name: 'Qwen Code',
    icon: 'QW',
    color: '#10B981',
    description: 'Alibaba Qwen Code CLI',
    configType: 'guide',
  },
}
