"""restore_provider_aliases

Revision ID: 58509c4c9ea4
Revises: e9dd6bfacf7f
Create Date: 2026-08-15 16:58:28.690790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58509c4c9ea4'
down_revision: Union[str, Sequence[str], None] = 'e9dd6bfacf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_aliases',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider'),
    sa.UniqueConstraint('alias', name='uq_provider_aliases_alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_aliases')
    # ### end Alembic commands ###
