"""add quota_cache table

Revision ID: 9a3d69805d5d
Revises: 0fae43bc2187
Create Date: 2026-08-09 05:05:31.690372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3d69805d5d'
down_revision: Union[str, Sequence[str], None] = '0fae43bc2187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_cache',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=100), nullable=True),
    sa.Column('quotas', sa.Text(), nullable=False),
    sa.Column('limit_reached', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['provider_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quota_cache')
    # ### end Alembic commands ###
