"""provider_models_custom

Revision ID: 9b1ea472199b
Revises: 58509c4c9ea4
Create Date: 2026-08-15 17:31:50.917910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1ea472199b'
down_revision: Union[str, Sequence[str], None] = '58509c4c9ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_models', sa.Column('custom', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_models', 'custom')
    # ### end Alembic commands ###
