"""add proxy_pool_id to provider_connections

Revision ID: d474b774ed85
Revises: a2b3c4d5e6f7
Create Date: 2026-05-17 22:43:31.723942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd474b774ed85'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_connections', sa.Column('proxy_pool_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'provider_connections', 'proxy_pools', ['proxy_pool_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider_connections', type_='foreignkey')
    op.drop_column('provider_connections', 'proxy_pool_id')
    # ### end Alembic commands ###
