"""drop_provider_aliases

Revision ID: e9dd6bfacf7f
Revises: eef1d0fdf2b6
Create Date: 2026-08-15 16:52:03.291065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9dd6bfacf7f'
down_revision: Union[str, Sequence[str], None] = 'eef1d0fdf2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_aliases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_aliases',
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('provider', name=op.f('provider_aliases_pkey')),
    sa.UniqueConstraint('alias', name=op.f('uq_provider_aliases_alias'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
