"""provider_aliases

Revision ID: eef1d0fdf2b6
Revises: a9b0c1d2e3f4
Create Date: 2026-08-15 15:16:45.162940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef1d0fdf2b6'
down_revision: Union[str, Sequence[str], None] = 'a9b0c1d2e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_aliases',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider'),
    sa.UniqueConstraint('alias', name='uq_provider_aliases_alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_aliases')
    # ### end Alembic commands ###
